### ISSUE TITLE
[Feature Request] Support Multi-Line Variables

### ISSUE THREAD

**Issue by Mikesch-mp** [vshn/signalilo#55]
Hello,

it would be nice to have the possibility to pass a [multi-line variable](https://icinga.com/docs/icinga-2/latest/doc/17-language-reference/#multi-line-string-literals) to icinga.

Thanks,
Carsten

**Comment by simu** [comment]
Hi Carsten,

As far as I can tell the multi-line string literals are simply a convenience feature for the Icinga2 config files, and are not required or supported by the API.

I successfully created and updated a service with a multi-line string variable by simply sending an alert with a label whose value contains newline (`\n`) characters to Signalilo.

Can you describe the use-case you have for multi-line String literals?

Thanks,
-- Simon

**Comment by Mikesch-mp** [comment]
For example sending hints to a variable that supports markdown on icingaweb2, see [#3814](https://github.com/Icinga/icingaweb2/pull/3814). Iam not sure it will work with a single line containing '\n'

**Comment by simu** [comment]
Hi Carsten,

Markdown works fine when provided in the alert as the `description` annotation, which is used to fill out the Icinga service "Notes" field (which supports markdown rendering).

Values for label `message` which contain `\n` characters are displayed as plugin output with line breaks as well:

![signalilo_multiline_md](https://user-images.githubusercontent.com/393160/108339694-08d54000-71d8-11eb-9968-3a5ea020071b.png)

Note that I'm usually using a sample JSON file containing an alert as it would be sent by Alertmanager when testing Signalilo instead of spinning up a whole Prometheus/Alertmanager stack. Here's the JSON I sent to Signalilo to produce the alert above:

```json
{
  "version": "4",
  "groupKey": "testgroup",
  "status": "firing",
  "receiver": "test",
  "groupLabels": { "testgroup": "testlabel" },
  "commonLabels": { "commonlabel": "exists" },
  "commonAnnotations": {},
  "externalURL": "http://alertmanager.example.com/path/to/alert",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "alertname": "demoalert-multiline",
        "commonlabel": "exists",
        "severity": "warning",
      },
      "annotations": {
        "summary": "Some test alert",
        "description": "# Testing support for Icinga2 markdown in notes\n\nMultiline String literals\n\n* List item\n* list item 2",
        "action_url": "http://wiki.vshn.net/alert/handling/page",
        "message": "Multi-line message test\n\nSome stuff is broken: 100% borked\nA second line\nAnd a third line",
        "icinga_number_production_level": "0"
      },
      "startsAt": "2019-03-26T14:36:16+01:00",
      "endsAt": "2019-03-26T14:46:16+01:00",
      "generatorURL": "http://prometheus-application-monitoring-1:9090/graph?g0.expr=up+%21%3D+1&g0.tab=1"
    }
  ]
}
```

**Comment by simu** [comment]
Hi @Mikesch-mp ,

I'm going to close this issue, since in my testing I verified that Signalilo is able to forward multi-line strings contained in alerts.
