### ISSUE TITLE
Handling of automatic heartbeat service is not working

### ISSUE THREAD

**Issue by Xavier-0965** [vshn/signalilo#56]
Hello,

we have created an heartbeat service WatchdogSHG, by setting a label 'heartbeat' as documented in [heartbeat Services](https://github.com/vshn/signalilo#heartbeat-services).

But in the log we can see that signalilo din't find the heartbeat service:

    {"level":"debug","msg":"Processing firing alert: alertname=WatchdogSHG, severity=critical, message=Diese Message wird erst angezeigt, wenn Signalilo nichts mehr schickt.\n","time":"2021-02-11T12:02:05+01:00"}
    {"level":"info","msg":"Creating alert as heartbeat with check interval 1m0s","time":"2021-02-11T12:02:05+01:00"}
    {"level":"info","msg":"creating service: WatchdogSHG_35df4c5608e7fd5e\n","time":"2021-02-11T12:02:05+01:00"}
    {"level":"debug","msg":"Executing ProcessCheckResult on icinga2 for WatchdogSHG_35df4c5608e7fd5e: exit status 0","time":"2021-02-11T12:02:05+01:00"}
    {"level":"debug","msg":"Processing resolved alert: alertname=WatchdogSHG, severity=none, message=This is an alert meant to ensure that the entire alerting pipeline is functional.\nThis alert is always firing, therefore it should always be firing in Alertmanager\nand always fire against a receiver. There are integrations with various notification\nmechanisms that send a notification when this alert is not firing. For example the\n\"DeadMansSnitch\" integration in PagerDuty.\n","time":"2021-02-11T12:02:05+01:00"}
    {"level":"info","msg":"Not processing resolved heartbeat for WatchdogSHG_c8b066e8d93e0f22","time":"2021-02-11T12:02:05+01:00"}
    {"level":"error","msg":"heartbeat: unable to get heartbeat service: Did not get 200 OK","time":"2021-02-11T12:02:58+01:00"}
    {"level":"error","msg":"sending heartbeat: Did not get 200 OK","time":"2021-02-11T12:02:58+01:00"}
    {"level":"error","msg":"heartbeat: unable to get heartbeat service: Did not get 200 OK","time":"2021-02-11T12:03:58+01:00"}
    {"level":"error","msg":"sending heartbeat: Did not get 200 OK","time":"2021-02-11T12:03:58+01:00"}

If I have really understood, the heartbeat service should be named `heartbeat`, see [serve.go#L76](https://github.com/vshn/signalilo/blob/595fc2a7bbe89966e59aa5a6e7c728e8c863d62a/serve.go#L76).

My Heartbeat Alert:

~~~
  - name: general.rules
    rules:
    - alert: WatchdogSHG
      annotations:
        message: |
          Diese Message wird erst angezeigt, wenn Signalilo nichts mehr schickt.
      expr: vector(1)
      labels:
        severity: critical
        heartbeat: 1m
~~~

Maybe I have missed something (again ;-) ).

Kind regards
Xavier

**Comment by simu** [comment]
Hi Xavier,

There's two concepts of "heartbeat" in Signalilo:

1. There's Signalilo's internal heartbeat, which is not configurable except for the interval. The internal heartbeat requires a service named `heartbeat` to exist on the Icinga2 ServiceHost for Signalilo, cf. https://github.com/vshn/signalilo#signalilo-heartbeat
2. Since v0.6, Signalilo supports dynamic heartbeat (or Watchdog) services forwarded by Alertmanager. Those can have any name, but require the label `heartbeat` to be set. Please note that you'll have to configure the `repeat_interval` in Alertmanager to be <= the value of the heartbeat label for these services, as otherwise Alertmanager will not send updates to Signalilo frequently enough to keep the check green in Icinga2, cf. https://github.com/vshn/signalilo#heartbeat-services

Looking at the log snippet you've provided, the custom heartbeat service `WatchdogSHD`, with Icinga service name `WatchdogSHG_35df4c5608e7fd5e`, gets created and processed correctly:

```
{"level":"debug","msg":"Processing firing alert: alertname=WatchdogSHG, severity=critical, message=Diese Message wird erst angezeigt, wenn Signalilo nichts mehr schickt.\n","time":"2021-02-11T12:02:05+01:00"}
{"level":"info","msg":"Creating alert as heartbeat with check interval 1m0s","time":"2021-02-11T12:02:05+01:00"}
{"level":"info","msg":"creating service: WatchdogSHG_35df4c5608e7fd5e\n","time":"2021-02-11T12:02:05+01:00"}
{"level":"debug","msg":"Executing ProcessCheckResult on icinga2 for WatchdogSHG_35df4c5608e7fd5e: exit status 0","time":"2021-02-11T12:02:05+01:00"}
```

However, it appears that your Icinga2 ServiceHost for Signalilo doesn't have the required `heartbeat` service, and so Signalilo fails to process its internal heartbeat:

```
{"level":"error","msg":"heartbeat: unable to get heartbeat service: Did not get 200 OK","time":"2021-02-11T12:02:58+01:00"}
{"level":"error","msg":"sending heartbeat: Did not get 200 OK","time":"2021-02-11T12:02:58+01:00"}
{"level":"error","msg":"heartbeat: unable to get heartbeat service: Did not get 200 OK","time":"2021-02-11T12:03:58+01:00"}
{"level":"error","msg":"sending heartbeat: Did not get 200 OK","time":"2021-02-11T12:03:58+01:00"}
```

The Signalilo internal heartbeat Icinga2 service should look something like (note that the dynamic `dummy_text` is not required):

```
/* Must be named "heartbeat" for Signalilo to find it */
object Service "heartbeat" {
  check_command = "dummy"
  /* Set check interval to 5min */
  check_interval = 300s
 
  /* Set the state to CRITICAL (2) if freshness checks fail. */
  vars.dummy_state = 2
 
  /* Use a runtime function to retrieve the last check time and more details. */
  vars.dummy_text = {{
    var service = get_service(macro("$host.name$"), macro("$service.name$"))
    var lastCheck = DateTime(service.last_check).to_string()
 
    return "Missing heartbeat pings from Signalilo. Last ping received at: " + lastCheck
  }}
 
  /* Associate the heartbeat service with the Signalilo ServiceHost in Icinga2 */
  host_name = "<signalilo_host>"
}
```

Hope this helps,
-- Simon

**Comment by Xavier-0965** [comment]
Hi Simon,

thank you very much for the quick answer and the help.

I didn't understood that there are 2 heartbeats:
    (1) <Signalilo> -- Heartbeat --> <Icinga>
    (2) <AlertManager> -- Watchdog or DeadManSwitch --> <Signalilo> --> <Icinga>  

The first one checks the communication between Signalilo and Icinga.
The second one checks the whole communication chain (AlertManager, Signalilo, Icinga).

Again it was a misunderstanding from my part :-)

Kind Regards
Xavier
