### ISSUE TITLE
description as Plugin Output? 

### ISSUE THREAD

**Issue by eyenx** [vshn/signalilo#79]
Hi

We are using signalilo togethere with the default alerts rules from kube-prometheus. All Rules are set there to use the annotation `description` rather than `message`. 

This means in our Icinga we see no plugin Output when an alert from `kube-proemtheus-stack` gets created. 

According to the Signalilo README only the `message` annotation is used for creating the `plugin_output` inside icinga:

```
Required annotations:

    description: mapped to notes.
    message: mapped to plugin_output.

```

This is a problem for us, as our icinga alerting system is going to send the `plugin_output` as a SMS and we don't parse the `notes` for alerting.

Could this be configured somehow, so that we can create the `plugin_output` from the `annotations['description']` rather then `annotations['message']`?

Thanks.

**Comment by eyenx** [comment]
@hairmare might have found the solution already https://github.com/vshn/signalilo/pull/44

**Comment by hairmare** [comment]
We are deploying Signalilo with Helm to monitor a standard kube-prometheus setup configured using kube-prometheus-stack. Since the stack is a bit inconsistent when it comes to alert annotations we had to add the following to our Helm values:

```yaml
 extraEnvVars:
 - name: SIGNALILO_ALERTMANAGER_PLUGINOUTPUT_ANNOTATIONS
   value: |
    description
    message
```

It's a multiline thing since that's what [kingpin uses to split arrays](https://github.com/alecthomas/kingpin/issues/102).
