### ISSUE TITLE
Icinga Service template name not configurable

### ISSUE THREAD

**Issue by mahauke** [vshn/signalilo#96]
Hi,

in our Icinga environment, the template name for generic services is not "generic-service", but "Generic Service" and we are not able to change this. Thus, signalilo fails to create services on Alerts with the error

```
500 Internal Server Error - Object could not be created. Error: Import references unknown template: 'generic-service'
```

I found out that the template name is hardcoded in your go-icinga2-client:
https://github.com/vshn/go-icinga2-client/blob/b157d0f48abed9f12ceb01a84f0db8021707010a/icinga2/service.go#L71

```
func (s *WebClient) CreateService(service Service) error {
	serviceCreate := ServiceCreate{Templates: []string{"generic-service"}, Attrs: service}
	// Strip "name" from create payload
	serviceCreate.Attrs.Name = ""
	err := s.CreateObject("/services/"+service.FullName(), serviceCreate)
	return err
}
```

Would it be an option for you to extend the go-icinga2-client with the option to configure the template name, and make this parameter configurable in signalilo?

**Comment by simu** [comment]
Hi,

We're not actively developing Signalilo and our fork of go-icinga2-client anymore, since we're in the process of moving away from Icinga2 for our centralized monitoring and alerting.

However, we're happy to accept PRs which introduce new features as long as they don't require existing users to update their configurations. For this issue this would mean introducing a new parameter for the template name with a default value of "generic-service" so that existing setups which use "generic-service" as the default template name continue working without any config changes.

**Comment by mahauke** [comment]
Hi Simon,

thank you for your honest feedback. Although I like the idea of signalilo, it is difficult to rely on with no active maintainer.

We will consider doing these changes on our own, but I cannot promise to.
